package euchre.gui;
import java.awt.*;

/**
 * Screen for the user to interact with the setup for a Network Game.
 *
 * @author Neil MacBay(nmmacbay)
 *
 */
public class SetupNetwork extends javax.swing.JFrame {

    /**
    * Constructs the form to interact with the setup of a network Game.
    */
    public SetupNetwork() {
        initComponents();
        centerScreen();
    }

    /**
     * Moves the jFrame to the center of the screen
     */
    private void centerScreen(){
        int xCenter;
        int yCenter;
        int xSize;
        int ySize;
        Point p = new Point();
        xSize = this.getSize().width;
        ySize = this.getSize().height;
        xCenter = Toolkit.getDefaultToolkit().getScreenSize().width/2;
        yCenter = Toolkit.getDefaultToolkit().getScreenSize().height/2;
        p.setLocation(xCenter - xSize/2, yCenter - ySize/2);
        this.setLocation(p);
        return;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jRadioButton3M = new javax.swing.JRadioButton();
        jRadioButton3E = new javax.swing.JRadioButton();
        jRadioButton2E = new javax.swing.JRadioButton();
        jRadioButton3H = new javax.swing.JRadioButton();
        jRadioButton2H = new javax.swing.JRadioButton();
        jRadioButton2M = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonGameStart = new javax.swing.JButton();
        jRadioButton1H = new javax.swing.JRadioButton();
        jTextFieldPlayerName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1M = new javax.swing.JRadioButton();
        jRadioButton1E = new javax.swing.JRadioButton();
        jTextFieldPlayerName1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextFieldPlayerName2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPlayerName3 = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Setup Network");

        buttonGroup3.add(jRadioButton3M);
        jRadioButton3M.setSelected(true);
        jRadioButton3M.setText("Medium");

        buttonGroup3.add(jRadioButton3E);
        jRadioButton3E.setText("Easy");

        buttonGroup2.add(jRadioButton2E);
        jRadioButton2E.setText("Easy");

        buttonGroup3.add(jRadioButton3H);
        jRadioButton3H.setText("Hard");

        buttonGroup2.add(jRadioButton2H);
        jRadioButton2H.setText("Hard");

        buttonGroup2.add(jRadioButton2M);
        jRadioButton2M.setSelected(true);
        jRadioButton2M.setText("Medium");

        jLabel1.setText("Host Name: ");

        jButtonGameStart.setText("Start Game");
        jButtonGameStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                launchNetworkGame(evt);
            }
        });

        buttonGroup1.add(jRadioButton1H);
        jRadioButton1H.setText("Hard");

        jTextFieldPlayerName.setText("Player 1");
        jTextFieldPlayerName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldPlayerNameMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldPlayerNameMouseEntered(evt);
            }
        });
        jTextFieldPlayerName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPlayerNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPlayerNameFocusLost(evt);
            }
        });

        jLabel4.setText("Computer Dificulty:");

        jLabel3.setText("Computer Dificulty: ");

        jLabel2.setText("Computer Dificulty: ");

        buttonGroup1.add(jRadioButton1M);
        jRadioButton1M.setSelected(true);
        jRadioButton1M.setText("Medium");

        buttonGroup1.add(jRadioButton1E);
        jRadioButton1E.setText("Easy");

        jTextFieldPlayerName1.setText("Player 2");
        jTextFieldPlayerName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldPlayerName1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldPlayerName1MouseEntered(evt);
            }
        });
        jTextFieldPlayerName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPlayerName1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPlayerName1FocusLost(evt);
            }
        });

        jLabel5.setText("Player Name: ");

        jLabel6.setText("Human Player:");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Yes");

        jTextFieldPlayerName2.setText("Player 3");
        jTextFieldPlayerName2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldPlayerName2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldPlayerName2MouseEntered(evt);
            }
        });
        jTextFieldPlayerName2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPlayerName2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPlayerName2FocusLost(evt);
            }
        });

        jLabel7.setText("Human Player:");

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Yes");

        jLabel8.setText("Player Name: ");

        jTextFieldPlayerName3.setText("Player 4");
        jTextFieldPlayerName3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldPlayerName3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldPlayerName3MouseEntered(evt);
            }
        });
        jTextFieldPlayerName3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPlayerName3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPlayerName3FocusLost(evt);
            }
        });

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Yes");

        jLabel9.setText("Human Player:");

        jLabel10.setText("Player Name: ");

        buttonGroup4.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Prefered Teammate");

        buttonGroup4.add(jRadioButton2);
        jRadioButton2.setText("Prefered Teammate");

        buttonGroup4.add(jRadioButton3);
        jRadioButton3.setText("Prefered Teammate");

        buttonGroup4.add(jRadioButton4);
        jRadioButton4.setText("Prefered Teammate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton1E, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton1M)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton1H))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPlayerName3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldPlayerName2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel1))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldPlayerName1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2E, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton2M)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2H)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(22, 22, 22)
                                    .addComponent(jRadioButton3E, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton3M)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioButton3H))))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonGameStart, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPlayerName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton1E)
                    .addComponent(jRadioButton1H)
                    .addComponent(jRadioButton1M))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPlayerName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton2E)
                    .addComponent(jRadioButton2H)
                    .addComponent(jRadioButton2M))
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jCheckBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPlayerName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton3E)
                    .addComponent(jRadioButton3M)
                    .addComponent(jRadioButton3H))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButtonGameStart, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPlayerNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPlayerNameMouseExited

}//GEN-LAST:event_jTextFieldPlayerNameMouseExited

    private void jTextFieldPlayerNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPlayerNameMouseEntered

}//GEN-LAST:event_jTextFieldPlayerNameMouseEntered

    private void jTextFieldPlayerNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPlayerNameFocusGained
        if (jTextFieldPlayerName.getText() == "Player 1"){
            jTextFieldPlayerName.setText("");
        }
}//GEN-LAST:event_jTextFieldPlayerNameFocusGained

    private void jTextFieldPlayerNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPlayerNameFocusLost
        if (jTextFieldPlayerName.getText() == ""){
            jTextFieldPlayerName.setText("Player 1");
        }
}//GEN-LAST:event_jTextFieldPlayerNameFocusLost

    private void jTextFieldPlayerName1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPlayerName1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlayerName1MouseExited

    private void jTextFieldPlayerName1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPlayerName1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlayerName1MouseEntered

    private void jTextFieldPlayerName1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPlayerName1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlayerName1FocusGained

    private void jTextFieldPlayerName1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPlayerName1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlayerName1FocusLost

    private void jTextFieldPlayerName2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPlayerName2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlayerName2MouseExited

    private void jTextFieldPlayerName2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPlayerName2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlayerName2MouseEntered

    private void jTextFieldPlayerName2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPlayerName2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlayerName2FocusGained

    private void jTextFieldPlayerName2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPlayerName2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlayerName2FocusLost

    private void jTextFieldPlayerName3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPlayerName3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlayerName3MouseExited

    private void jTextFieldPlayerName3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPlayerName3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlayerName3MouseEntered

    private void jTextFieldPlayerName3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPlayerName3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlayerName3FocusGained

    private void jTextFieldPlayerName3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPlayerName3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlayerName3FocusLost

    /**
    * Launch a Network game with the users and the options that they selected for their game.
    */
    private void launchNetworkGame(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launchNetworkGame
        new GameBoard().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_launchNetworkGame

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButtonGameStart;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton1E;
    private javax.swing.JRadioButton jRadioButton1H;
    private javax.swing.JRadioButton jRadioButton1M;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton2E;
    private javax.swing.JRadioButton jRadioButton2H;
    private javax.swing.JRadioButton jRadioButton2M;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton3E;
    private javax.swing.JRadioButton jRadioButton3H;
    private javax.swing.JRadioButton jRadioButton3M;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldPlayerName;
    private javax.swing.JTextField jTextFieldPlayerName1;
    private javax.swing.JTextField jTextFieldPlayerName2;
    private javax.swing.JTextField jTextFieldPlayerName3;
    // End of variables declaration//GEN-END:variables

}
